export const countries = [
  {
    countryName: 'Afghanistan',
    dialCode: '+93',
    numberOfDigits: 9,
    countryTwoLetters: 'af',
  },
  {
    countryName: 'Albania',
    dialCode: '+355',
    numberOfDigits: 8,
    countryTwoLetters: 'al',
  },
  {
    countryName: 'Algeria',
    dialCode: '+213',
    numberOfDigits: 9,
    countryTwoLetters: 'dz',
  },
  {
    countryName: 'Andorra',
    dialCode: '+376',
    numberOfDigits: 6,
    countryTwoLetters: 'ad',
  },
  {
    countryName: 'Angola',
    dialCode: '+244',
    numberOfDigits: 9,
    countryTwoLetters: 'ao',
  },
  {
    countryName: 'Antigua and Barbuda',
    dialCode: '+1268',
    numberOfDigits: 7,
    countryTwoLetters: 'ag',
  },
  {
    countryName: 'Argentina',
    dialCode: '+54',
    numberOfDigits: 10,
    countryTwoLetters: 'ar',
  },
  {
    countryName: 'Armenia',
    dialCode: '+374',
    numberOfDigits: 8,
    countryTwoLetters: 'am',
  },
  {
    countryName: 'Australia',
    dialCode: '+61',
    numberOfDigits: 9,
    countryTwoLetters: 'au',
  },
  {
    countryName: 'Austria',
    dialCode: '+43',
    numberOfDigits: 10,
    countryTwoLetters: 'at',
  },
  {
    countryName: 'Azerbaijan',
    dialCode: '+994',
    numberOfDigits: 9,
    countryTwoLetters: 'az',
  },
  {
    countryName: 'Bahamas',
    dialCode: '+1242',
    numberOfDigits: 7,
    countryTwoLetters: 'bs',
  },
  {
    countryName: 'Bahrain',
    dialCode: '+973',
    numberOfDigits: 8,
    countryTwoLetters: 'bh',
  },
  {
    countryName: 'Bangladesh',
    dialCode: '+880',
    numberOfDigits: 10,
    countryTwoLetters: 'bd',
  },
  {
    countryName: 'Barbados',
    dialCode: '+1246',
    numberOfDigits: 7,
    countryTwoLetters: 'bb',
  },
  {
    countryName: 'Belarus',
    dialCode: '+375',
    numberOfDigits: 9,
    countryTwoLetters: 'by',
  },
  {
    countryName: 'Belgium',
    dialCode: '+32',
    numberOfDigits: 9,
    countryTwoLetters: 'be',
  },
  {
    countryName: 'Belize',
    dialCode: '+501',
    numberOfDigits: 7,
    countryTwoLetters: 'bz',
  },
  {
    countryName: 'Benin',
    dialCode: '+229',
    numberOfDigits: 8,
    countryTwoLetters: 'bj',
  },
  {
    countryName: 'Bhutan',
    dialCode: '+975',
    numberOfDigits: 8,
    countryTwoLetters: 'bt',
  },
  {
    countryName: 'Bolivia',
    dialCode: '+591',
    numberOfDigits: 8,
    countryTwoLetters: 'bo',
  },
  {
    countryName: 'Bosnia and Herzegovina',
    dialCode: '+387',
    numberOfDigits: 8,
    countryTwoLetters: 'ba',
  },
  {
    countryName: 'Botswana',
    dialCode: '+267',
    numberOfDigits: 7,
    countryTwoLetters: 'bw',
  },
  {
    countryName: 'Brazil',
    dialCode: '+55',
    numberOfDigits: 11,
    countryTwoLetters: 'br',
  },
  {
    countryName: 'Brunei Darussalam',
    dialCode: '+673',
    numberOfDigits: 7,
    countryTwoLetters: 'bn',
  },
  {
    countryName: 'Bulgaria',
    dialCode: '+359',
    numberOfDigits: 8,
    countryTwoLetters: 'bg',
  },
  {
    countryName: 'Burkina Faso',
    dialCode: '+226',
    numberOfDigits: 8,
    countryTwoLetters: 'bf',
  },
  {
    countryName: 'Burundi',
    dialCode: '+257',
    numberOfDigits: 8,
    countryTwoLetters: 'bi',
  },
  {
    countryName: 'Cambodia',
    dialCode: '+855',
    numberOfDigits: 8,
    countryTwoLetters: 'kh',
  },
  {
    countryName: 'Cameroon',
    dialCode: '+237',
    numberOfDigits: 9,
    countryTwoLetters: 'cm',
  },
  {
    countryName: 'Canada',
    dialCode: '+1',
    numberOfDigits: 10,
    countryTwoLetters: 'ca',
  },
  {
    countryName: 'Cape Verde',
    dialCode: '+238',
    numberOfDigits: 7,
    countryTwoLetters: 'cv',
  },
  {
    countryName: 'Cayman Islands',
    dialCode: '+1345',
    numberOfDigits: 7,
    countryTwoLetters: 'ky',
  },
  {
    countryName: 'Central African Republic',
    dialCode: '+236',
    numberOfDigits: 8,
    countryTwoLetters: 'cf',
  },
  {
    countryName: 'Chad',
    dialCode: '+235',
    numberOfDigits: 7,
    countryTwoLetters: 'td',
  },
  {
    countryName: 'Chile',
    dialCode: '+56',
    numberOfDigits: 9,
    countryTwoLetters: 'cl',
  },
  {
    countryName: 'China',
    dialCode: '+86',
    numberOfDigits: 11,
    countryTwoLetters: 'cn',
  },
  {
    countryName: 'Colombia',
    dialCode: '+57',
    numberOfDigits: 10,
    countryTwoLetters: 'co',
  },
  {
    countryName: 'Comoros',
    dialCode: '+269',
    numberOfDigits: 3,
    countryTwoLetters: 'km',
  },
  {
    countryName: 'Congo',
    dialCode: '+242',
    numberOfDigits: 9,
    countryTwoLetters: 'cg',
  },
  {
    countryName: 'Costa Rica',
    dialCode: '+506',
    numberOfDigits: 8,
    countryTwoLetters: 'cr',
  },
  {
    countryName: "Côte d'Ivoire",
    dialCode: '+225',
    numberOfDigits: 8,
    countryTwoLetters: 'ci',
  },
  {
    countryName: 'Croatia',
    dialCode: '+385',
    numberOfDigits: 9,
    countryTwoLetters: 'hr',
  },
  {
    countryName: 'Cuba',
    dialCode: '+53',
    numberOfDigits: 8,
    countryTwoLetters: 'cu',
  },
  {
    countryName: 'Cyprus',
    dialCode: '+357',
    numberOfDigits: 8,
    countryTwoLetters: 'cy',
  },
  {
    countryName: 'Czech Republic',
    dialCode: '+420',
    numberOfDigits: 9,
    countryTwoLetters: 'cz',
  },
  {
    countryName: "Democratic People's Republic of Korea",
    dialCode: '+850',
    numberOfDigits: 9,
    countryTwoLetters: 'kp',
  },
  {
    countryName: 'Democratic Republic of the Congo',
    dialCode: '+243',
    numberOfDigits: 9,
    countryTwoLetters: 'cd',
  },
  {
    countryName: 'Denmark',
    dialCode: '+45',
    numberOfDigits: 8,
    countryTwoLetters: 'dk',
  },
  {
    countryName: 'Djibouti',
    dialCode: '+253',
    numberOfDigits: 8,
    countryTwoLetters: 'dj',
  },
  {
    countryName: 'Dominica',
    dialCode: '+1767',
    numberOfDigits: 7,
    countryTwoLetters: 'dm',
  },
  {
    countryName: 'Dominican Republic',
    dialCode: '+1809',
    numberOfDigits: 10,
    countryTwoLetters: 'do',
  },
  {
    countryName: 'Ecuador',
    dialCode: '+593',
    numberOfDigits: 9,
    countryTwoLetters: 'ec',
  },
  {
    countryName: 'Egypt',
    dialCode: '+20',
    numberOfDigits: 11,
    countryTwoLetters: 'eg',
  },
  {
    countryName: 'El Salvador',
    dialCode: '+503',
    numberOfDigits: 8,
    countryTwoLetters: 'sv',
  },
  {
    countryName: 'Equatorial Guinea',
    dialCode: '+240',
    numberOfDigits: 9,
    countryTwoLetters: 'gq',
  },
  {
    countryName: 'Eritrea',
    dialCode: '+291',
    numberOfDigits: 7,
    countryTwoLetters: 'er',
  },
  {
    countryName: 'Estonia',
    dialCode: '+372',
    numberOfDigits: 8,
    countryTwoLetters: 'ee',
  },
  {
    countryName: 'Eswatini',
    dialCode: '+268',
    numberOfDigits: 8,
    countryTwoLetters: 'sz',
  },
  {
    countryName: 'Ethiopia',
    dialCode: '+251',
    numberOfDigits: 9,
    countryTwoLetters: 'et',
  },
  {
    countryName: 'Falkland Islands (Malvinas)',
    dialCode: '+500',
    numberOfDigits: 7,
    countryTwoLetters: 'fk',
  },
  {
    countryName: 'Faroe Islands',
    dialCode: '+298',
    numberOfDigits: 8,
    countryTwoLetters: 'fo',
  },
  {
    countryName: 'Fiji',
    dialCode: '+679',
    numberOfDigits: 7,
    countryTwoLetters: 'fj',
  },
  {
    countryName: 'Finland',
    dialCode: '+358',
    numberOfDigits: 9,
    countryTwoLetters: 'fi',
  },
  {
    countryName: 'France',
    dialCode: '+33',
    numberOfDigits: 9,
    countryTwoLetters: 'fr',
  },
  {
    countryName: 'French Guiana',
    dialCode: '+594',
    numberOfDigits: 6,
    countryTwoLetters: 'gf',
  },
  {
    countryName: 'Gabon',
    dialCode: '+241',
    numberOfDigits: 8,
    countryTwoLetters: 'ga',
  },
  {
    countryName: 'Gambia',
    dialCode: '+220',
    numberOfDigits: 7,
    countryTwoLetters: 'gm',
  },
  {
    countryName: 'Georgia',
    dialCode: '+995',
    numberOfDigits: 9,
    countryTwoLetters: 'ge',
  },
  {
    countryName: 'Germany',
    dialCode: '+49',
    numberOfDigits: 11,
    countryTwoLetters: 'de',
  },
  {
    countryName: 'Ghana',
    dialCode: '+233',
    numberOfDigits: 8,
    countryTwoLetters: 'gh',
  },
  {
    countryName: 'Gibraltar',
    dialCode: '+350',
    numberOfDigits: 5,
    countryTwoLetters: 'gi',
  },
  {
    countryName: 'Greece',
    dialCode: '+30',
    numberOfDigits: 8,
    countryTwoLetters: 'gr',
  },
  {
    countryName: 'Greenland',
    dialCode: '+299',
    numberOfDigits: 8,
    countryTwoLetters: 'gl',
  },
  {
    countryName: 'Grenada',
    dialCode: '+1473',
    numberOfDigits: 7,
    countryTwoLetters: 'gd',
  },
  {
    countryName: 'Guadeloupe',
    dialCode: '+590',
    numberOfDigits: 6,
    countryTwoLetters: 'gp',
  },
  {
    countryName: 'Guam',
    dialCode: '+1671',
    numberOfDigits: 7,
    countryTwoLetters: 'gu',
  },
  {
    countryName: 'Guatemala',
    dialCode: '+502',
    numberOfDigits: 8,
    countryTwoLetters: 'gt',
  },
  {
    countryName: 'Guinea',
    dialCode: '+224',
    numberOfDigits: 9,
    countryTwoLetters: 'gn',
  },
  {
    countryName: 'Guinea-Bissau',
    dialCode: '+245',
    numberOfDigits: 8,
    countryTwoLetters: 'gw',
  },
  {
    countryName: 'Guyana',
    dialCode: '+592',
    numberOfDigits: 7,
    countryTwoLetters: 'gy',
  },
  {
    countryName: 'Haiti',
    dialCode: '+509',
    numberOfDigits: 8,
    countryTwoLetters: 'ht',
  },
  {
    countryName: 'Holy See (Vatican City State)',
    dialCode: '+379',
    numberOfDigits: 9,
    countryTwoLetters: 'va',
  },
  {
    countryName: 'Honduras',
    dialCode: '+504',
    numberOfDigits: 8,
    countryTwoLetters: 'hn',
  },
  {
    countryName: 'Hong Kong',
    dialCode: '+852',
    numberOfDigits: 8,
    countryTwoLetters: 'hk',
  },
  {
    countryName: 'Hungary',
    dialCode: '+36',
    numberOfDigits: 9,
    countryTwoLetters: 'hu',
  },
  {
    countryName: 'Iceland',
    dialCode: '+354',
    numberOfDigits: 7,
    countryTwoLetters: 'is',
  },
  {
    countryName: 'India',
    dialCode: '+91',
    numberOfDigits: 10,
    countryTwoLetters: 'in',
  },
  {
    countryName: 'Indonesia',
    dialCode: '+62',
    numberOfDigits: 9,
    countryTwoLetters: 'id',
  },
  {
    countryName: 'Iran (Islamic Republic of)',
    dialCode: '+98',
    numberOfDigits: 10,
    countryTwoLetters: 'ir',
  },
  {
    countryName: 'Iraq',
    dialCode: '+964',
    numberOfDigits: 9,
    countryTwoLetters: 'iq',
  },
  {
    countryName: 'Ireland',
    dialCode: '+353',
    numberOfDigits: 9,
    countryTwoLetters: 'ie',
  },
  {
    countryName: 'Isle of Man',
    dialCode: '+44',
    numberOfDigits: 6,
    countryTwoLetters: 'im',
  },
  {
    countryName: 'Israel',
    dialCode: '+972',
    numberOfDigits: 9,
    countryTwoLetters: 'il',
  },
  {
    countryName: 'Italy',
    dialCode: '+39',
    numberOfDigits: 10,
    countryTwoLetters: 'it',
  },
  {
    countryName: 'Jamaica',
    dialCode: '+1876',
    numberOfDigits: 7,
    countryTwoLetters: 'jm',
  },
  {
    countryName: 'Japan',
    dialCode: '+81',
    numberOfDigits: 10,
    countryTwoLetters: 'jp',
  },
  {
    countryName: 'Jordan',
    dialCode: '+962',
    numberOfDigits: 9,
    countryTwoLetters: 'jo',
  },
  {
    countryName: 'Kazakhstan',
    dialCode: '+7',
    numberOfDigits: 9,
    countryTwoLetters: 'kz',
  },
  {
    countryName: 'Kenya',
    dialCode: '+254',
    numberOfDigits: 9,
    countryTwoLetters: 'ke',
  },
  {
    countryName: 'Kiribati',
    dialCode: '+686',
    numberOfDigits: 8,
    countryTwoLetters: 'ki',
  },
  {
    countryName: 'Kuwait',
    dialCode: '+965',
    numberOfDigits: 8,
    countryTwoLetters: 'kw',
  },
  {
    countryName: 'Kyrgyzstan',
    dialCode: '+996',
    numberOfDigits: 9,
    countryTwoLetters: 'kg',
  },
  {
    countryName: "Lao People's Democratic Republic",
    dialCode: '+856',
    numberOfDigits: 8,
    countryTwoLetters: 'la',
  },
  {
    countryName: 'Latvia',
    dialCode: '+371',
    numberOfDigits: 8,
    countryTwoLetters: 'lv',
  },
  {
    countryName: 'Lebanon',
    dialCode: '+961',
    numberOfDigits: 8,
    countryTwoLetters: 'lb',
  },
  {
    countryName: 'Lesotho',
    dialCode: '+266',
    numberOfDigits: 8,
    countryTwoLetters: 'ls',
  },
  {
    countryName: 'Liberia',
    dialCode: '+231',
    numberOfDigits: 8,
    countryTwoLetters: 'lr',
  },
  {
    countryName: 'Libya',
    dialCode: '+218',
    numberOfDigits: 9,
    countryTwoLetters: 'ly',
  },
  {
    countryName: 'Liechtenstein',
    dialCode: '+423',
    numberOfDigits: 6,
    countryTwoLetters: 'li',
  },
  {
    countryName: 'Lithuania',
    dialCode: '+370',
    numberOfDigits: 8,
    countryTwoLetters: 'lt',
  },
  {
    countryName: 'Luxembourg',
    dialCode: '+352',
    numberOfDigits: 9,
    countryTwoLetters: 'lu',
  },
  {
    countryName: 'Macao',
    dialCode: '+853',
    numberOfDigits: 8,
    countryTwoLetters: 'mo',
  },
  {
    countryName: 'Madagascar',
    dialCode: '+261',
    numberOfDigits: 2,
    countryTwoLetters: 'mg',
  },
  {
    countryName: 'Malawi',
    dialCode: '+265',
    numberOfDigits: 8,
    countryTwoLetters: 'mw',
  },
  {
    countryName: 'Malaysia',
    dialCode: '+60',
    numberOfDigits: 9,
    countryTwoLetters: 'my',
  },
  {
    countryName: 'Maldives',
    dialCode: '+960',
    numberOfDigits: 7,
    countryTwoLetters: 'mv',
  },
  {
    countryName: 'Mali',
    dialCode: '+223',
    numberOfDigits: 8,
    countryTwoLetters: 'ml',
  },
  {
    countryName: 'Malta',
    dialCode: '+356',
    numberOfDigits: 8,
    countryTwoLetters: 'mt',
  },
  {
    countryName: 'Marshall Islands',
    dialCode: '+692',
    numberOfDigits: 7,
    countryTwoLetters: 'mh',
  },
  {
    countryName: 'Mauritania',
    dialCode: '+222',
    numberOfDigits: 8,
    countryTwoLetters: 'mr',
  },
  {
    countryName: 'Mauritius',
    dialCode: '+230',
    numberOfDigits: 8,
    countryTwoLetters: 'mu',
  },
  {
    countryName: 'Mexico',
    dialCode: '+52',
    numberOfDigits: 10,
    countryTwoLetters: 'mx',
  },
  {
    countryName: 'Micronesia (Federated States of)',
    dialCode: '+691',
    numberOfDigits: 7,
    countryTwoLetters: 'fm',
  },
  {
    countryName: 'Monaco',
    dialCode: '+377',
    numberOfDigits: 9,
    countryTwoLetters: 'mc',
  },
  {
    countryName: 'Mongolia',
    dialCode: '+976',
    numberOfDigits: 8,
    countryTwoLetters: 'mn',
  },
  {
    countryName: 'Montenegro',
    dialCode: '+382',
    numberOfDigits: 8,
    countryTwoLetters: 'me',
  },
  {
    countryName: 'Montserrat',
    dialCode: '+1664',
    numberOfDigits: 7,
    countryTwoLetters: 'ms',
  },
  {
    countryName: 'Morocco',
    dialCode: '+212',
    numberOfDigits: 9,
    countryTwoLetters: 'ma',
  },
  {
    countryName: 'Mozambique',
    dialCode: '+258',
    numberOfDigits: 8,
    countryTwoLetters: 'mz',
  },
  {
    countryName: 'Myanmar',
    dialCode: '+95',
    numberOfDigits: 9,
    countryTwoLetters: 'mm',
  },
  {
    countryName: 'Namibia',
    dialCode: '+264',
    numberOfDigits: 9,
    countryTwoLetters: 'na',
  },
  {
    countryName: 'Nauru',
    dialCode: '+674',
    numberOfDigits: 7,
    countryTwoLetters: 'nr',
  },
  {
    countryName: 'Nepal',
    dialCode: '+977',
    numberOfDigits: 10,
    countryTwoLetters: 'np',
  },
  {
    countryName: 'Netherlands',
    dialCode: '+31',
    numberOfDigits: 9,
    countryTwoLetters: 'nl',
  },
  {
    countryName: 'New Caledonia',
    dialCode: '+689',
    numberOfDigits: 6,
    countryTwoLetters: 'nc',
  },
  {
    countryName: 'New Zealand',
    dialCode: '+64',
    numberOfDigits: 10,
    countryTwoLetters: 'nz',
  },
  {
    countryName: 'Nicaragua',
    dialCode: '+505',
    numberOfDigits: 8,
    countryTwoLetters: 'ni',
  },
  {
    countryName: 'Niger',
    dialCode: '+227',
    numberOfDigits: 8,
    countryTwoLetters: 'ne',
  },
  {
    countryName: 'Nigeria',
    dialCode: '+234',
    numberOfDigits: 11,
    countryTwoLetters: 'ng',
  },
  {
    countryName: 'Niue',
    dialCode: '+683',
    numberOfDigits: 6,
    countryTwoLetters: 'nu',
  },
  {
    countryName: 'Norfolk Island',
    dialCode: '+672',
    numberOfDigits: 6,
    countryTwoLetters: 'nf',
  },
  {
    countryName: 'North Korea',
    dialCode: '+850',
    numberOfDigits: 9,
    countryTwoLetters: 'kp',
  },
  {
    countryName: 'Northern Mariana Islands',
    dialCode: '+1670',
    numberOfDigits: 7,
    countryTwoLetters: 'mp',
  },
  {
    countryName: 'Norway',
    dialCode: '+47',
    numberOfDigits: 8,
    countryTwoLetters: 'no',
  },
  {
    countryName: 'Oman',
    dialCode: '+968',
    numberOfDigits: 8,
    countryTwoLetters: 'om',
  },
  {
    countryName: 'Pakistan',
    dialCode: '+92',
    numberOfDigits: 10,
    countryTwoLetters: 'pk',
  },
  {
    countryName: 'Palau',
    dialCode: '+680',
    numberOfDigits: 7,
    countryTwoLetters: 'pw',
  },
  {
    countryName: 'Panama',
    dialCode: '+507',
    numberOfDigits: 8,
    countryTwoLetters: 'pa',
  },
  {
    countryName: 'Papua New Guinea',
    dialCode: '+675',
    numberOfDigits: 7,
    countryTwoLetters: 'pg',
  },
  {
    countryName: 'Paraguay',
    dialCode: '+595',
    numberOfDigits: 9,
    countryTwoLetters: 'py',
  },
  {
    countryName: 'Peru',
    dialCode: '+51',
    numberOfDigits: 9,
    countryTwoLetters: 'pe',
  },
  {
    countryName: 'Philippines',
    dialCode: '+63',
    numberOfDigits: 10,
    countryTwoLetters: 'ph',
  },
  {
    countryName: 'Pitcairn',
    dialCode: '+64',
    numberOfDigits: 3,
    countryTwoLetters: 'pn',
  },
  {
    countryName: 'Poland',
    dialCode: '+48',
    numberOfDigits: 9,
    countryTwoLetters: 'pl',
  },
  {
    countryName: 'Portugal',
    dialCode: '+351',
    numberOfDigits: 9,
    countryTwoLetters: 'pt',
  },
  {
    countryName: 'Puerto Rico',
    dialCode: '+1',
    numberOfDigits: 10,
    countryTwoLetters: 'pr',
  },
  {
    countryName: 'Qatar',
    dialCode: '+974',
    numberOfDigits: 8,
    countryTwoLetters: 'qa',
  },
  {
    countryName: 'Republic of Korea',
    dialCode: '+82',
    numberOfDigits: 10,
    countryTwoLetters: 'kr',
  },
  {
    countryName: 'Republic of Moldova',
    dialCode: '+373',
    numberOfDigits: 8,
    countryTwoLetters: 'md',
  },
  {
    countryName: 'Réunion',
    dialCode: '+262',
    numberOfDigits: 6,
    countryTwoLetters: 're',
  },
  {
    countryName: 'Romania',
    dialCode: '+40',
    numberOfDigits: 9,
    countryTwoLetters: 'ro',
  },
  {
    countryName: 'Russian Federation',
    dialCode: '+7',
    numberOfDigits: 10,
    countryTwoLetters: 'ru',
  },
  {
    countryName: 'Rwanda',
    dialCode: '+250',
    numberOfDigits: 9,
    countryTwoLetters: 'rw',
  },
  {
    countryName: 'Saint Kitts and Nevis',
    dialCode: '+1869',
    numberOfDigits: 7,
    countryTwoLetters: 'kn',
  },
  {
    countryName: 'Saint Lucia',
    dialCode: '+1758',
    numberOfDigits: 7,
    countryTwoLetters: 'lc',
  },
  {
    countryName: 'Saint Martin (French part)',
    dialCode: '+590',
    numberOfDigits: 6,
    countryTwoLetters: 'mf',
  },
  {
    countryName: 'Saint Pierre and Miquelon',
    dialCode: '+508',
    numberOfDigits: 6,
    countryTwoLetters: 'pm',
  },
  {
    countryName: 'Saint Vincent and the Grenadines',
    dialCode: '+1784',
    numberOfDigits: 7,
    countryTwoLetters: 'vc',
  },
  {
    countryName: 'Samoa',
    dialCode: '+685',
    numberOfDigits: 7,
    countryTwoLetters: 'ws',
  },
  {
    countryName: 'San Marino',
    dialCode: '+378',
    numberOfDigits: 9,
    countryTwoLetters: 'sm',
  },
  {
    countryName: 'Sao Tome and Principe',
    dialCode: '+239',
    numberOfDigits: 9,
    countryTwoLetters: 'st',
  },
  {
    countryName: 'Saudi Arabia',
    dialCode: '+966',
    numberOfDigits: 9,
    countryTwoLetters: 'sa',
  },
  {
    countryName: 'Senegal',
    dialCode: '+221',
    numberOfDigits: 8,
    countryTwoLetters: 'sn',
  },
  {
    countryName: 'Serbia',
    dialCode: '+381',
    numberOfDigits: 8,
    countryTwoLetters: 'rs',
  },
  {
    countryName: 'Seychelles',
    dialCode: '+248',
    numberOfDigits: 7,
    countryTwoLetters: 'sc',
  },
  {
    countryName: 'Sierra Leone',
    dialCode: '+232',
    numberOfDigits: 8,
    countryTwoLetters: 'sl',
  },
  {
    countryName: 'Singapore',
    dialCode: '+65',
    numberOfDigits: 8,
    countryTwoLetters: 'sg',
  },
  {
    countryName: 'Sint Maarten (Dutch part)',
    dialCode: '+1721',
    numberOfDigits: 7,
  },
  {
    countryName: 'Slovakia',
    dialCode: '+421',
    numberOfDigits: 9,
    countryTwoLetters: 'sk',
  },
  {
    countryName: 'Slovenia',
    dialCode: '+386',
    numberOfDigits: 8,
    countryTwoLetters: 'si',
  },
  {
    countryName: 'Solomon Islands',
    dialCode: '+677',
    numberOfDigits: 7,
    countryTwoLetters: 'sb',
  },
  {
    countryName: 'Somalia',
    dialCode: '+252',
    numberOfDigits: 9,
    countryTwoLetters: 'so',
  },
  {
    countryName: 'South Africa',
    dialCode: '+27',
    numberOfDigits: 9,
    countryTwoLetters: 'za',
  },
  {
    countryName: 'South Sudan',
    dialCode: '+211',
    numberOfDigits: 9,
    countryTwoLetters: 'ss',
  },
  {
    countryName: 'Spain',
    dialCode: '+34',
    numberOfDigits: 9,
    countryTwoLetters: 'es',
  },
  {
    countryName: 'Sri Lanka',
    dialCode: '+94',
    numberOfDigits: 9,
    countryTwoLetters: 'lk',
  },
  {
    countryName: 'Sudan',
    dialCode: '+249',
    numberOfDigits: 9,
    countryTwoLetters: 'sd',
  },
  {
    countryName: 'Suriname',
    dialCode: '+597',
    numberOfDigits: 7,
    countryTwoLetters: 'sr',
  },
  {
    countryName: 'Swaziland',
    dialCode: '+268',
    numberOfDigits: 8,
    countryTwoLetters: 'sz',
  },
  {
    countryName: 'Sweden',
    dialCode: '+46',
    numberOfDigits: 8,
    countryTwoLetters: 'se',
  },
  {
    countryName: 'Switzerland',
    dialCode: '+41',
    numberOfDigits: 9,
    countryTwoLetters: 'ch',
  },
  {
    countryName: 'Syrian Arab Republic',
    dialCode: '+963',
    numberOfDigits: 9,
    countryTwoLetters: 'sy',
  },
  {
    countryName: 'Tajikistan',
    dialCode: '+992',
    numberOfDigits: 8,
    countryTwoLetters: 'tj',
  },
  {
    countryName: 'Thailand',
    dialCode: '+66',
    numberOfDigits: 9,
    countryTwoLetters: 'th',
  },
  {
    countryName: 'The former Yugoslav Republic of Macedonia',
    dialCode: '+389',
    numberOfDigits: 8,
    countryTwoLetters: 'mk',
  },
  {
    countryName: 'Timor-Leste',
    dialCode: '+670',
    numberOfDigits: 7,
    countryTwoLetters: 'tl',
  },
  {
    countryName: 'Togo',
    dialCode: '+228',
    numberOfDigits: 8,
    countryTwoLetters: 'tg',
  },
  {
    countryName: 'Tonga',
    dialCode: '+676',
    numberOfDigits: 7,
    countryTwoLetters: 'to',
  },
  {
    countryName: 'Trinidad and Tobago',
    dialCode: '+1868',
    numberOfDigits: 7,
    countryTwoLetters: 'tt',
  },
  {
    countryName: 'Tunisia',
    dialCode: '+216',
    numberOfDigits: 8,
    countryTwoLetters: 'tn',
  },
  {
    countryName: 'Turkey',
    dialCode: '+90',
    numberOfDigits: 10,
    countryTwoLetters: 'tr',
  },
  {
    countryName: 'Turkmenistan',
    dialCode: '+993',
    numberOfDigits: 8,
    countryTwoLetters: 'tm',
  },
  {
    countryName: 'Tuvalu',
    dialCode: '+688',
    numberOfDigits: 7,
    countryTwoLetters: 'tv',
  },
  {
    countryName: 'Uganda',
    dialCode: '+256',
    numberOfDigits: 9,
    countryTwoLetters: 'ug',
  },
  {
    countryName: 'Ukraine',
    dialCode: '+380',
    numberOfDigits: 9,
    countryTwoLetters: 'ua',
  },
  {
    countryName: 'United Arab Emirates',
    dialCode: '+971',
    numberOfDigits: 9,
    countryTwoLetters: 'ae',
  },
  {
    countryName: 'United Kingdom of Great Britain and Northern Ireland',
    dialCode: '+44',
    numberOfDigits: 10,
    countryTwoLetters: 'gb',
  },
  {
    countryName: 'United Republic of Tanzania',
    dialCode: '+255',
    numberOfDigits: 7,
    countryTwoLetters: 'tz',
  },
  {
    countryName: 'United States',
    dialCode: '+1',
    numberOfDigits: 10,
    countryTwoLetters: 'us',
  },
  {
    countryName: 'Uruguay',
    dialCode: '+598',
    numberOfDigits: 8,
    countryTwoLetters: 'uy',
  },
  {
    countryName: 'Uzbekistan',
    dialCode: '+998',
    numberOfDigits: 9,
    countryTwoLetters: 'uz',
  },
  {
    countryName: 'Vanuatu',
    dialCode: '+678',
    numberOfDigits: 7,
    countryTwoLetters: 'vu',
  },
  {
    countryName: 'Venezuela (Bolivarian Republic of)',
    dialCode: '+58',
    numberOfDigits: 8,
    countryTwoLetters: 've',
  },
  {
    countryName: 'Viet Nam',
    dialCode: '+84',
    numberOfDigits: 9,
    countryTwoLetters: 'vn',
  },
  {
    countryName: 'Virgin Islands (British)',
    dialCode: '+1284',
    numberOfDigits: 7,
    countryTwoLetters: 'vg',
  },
  {
    countryName: 'Virgin Islands (U.S.)',
    dialCode: '+1340',
    numberOfDigits: 7,
    countryTwoLetters: 'vi',
  },
  {
    countryName: 'Wallis and Futuna',
    dialCode: '+681',
    numberOfDigits: 6,
    countryTwoLetters: 'wf',
  },
  {
    countryName: 'Yemen',
    dialCode: '+967',
    numberOfDigits: 9,
    countryTwoLetters: 'ye',
  },
  {
    countryName: 'Zambia',
    dialCode: '+260',
    numberOfDigits: 9,
    countryTwoLetters: 'zm',
  },
  {
    countryName: 'Zimbabwe',
    dialCode: '+263',
    numberOfDigits: 9,
    countryTwoLetters: 'zw',
  },
];
