export enum AppRoutes {
  baseAppTitle = 'YSSR - ',
  layout = '',
  login = 'login',
  forgetPassword = 'forget-password',
  resetPassword = 'reset-password',
  verificationCode = 'verification-code',
  customers = 'customers',
  worker = 'workers',
  settings = 'settings',
  add = 'add',
  edit = 'update',
  contracts = 'contracts',
  waivers = 'waivers',
  waiversSpecifications = 'waivers-specifications',
  suretyTransfer = 'surety-transfers',
  rents = 'rents',
  refund = 'refund-management',
  housing = 'housing',
  offices = 'offices',
  branches = 'branches',
  users = 'users',
  financial = 'financial-management',
}
